# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://freefeet.in
title: Freefeet
email: aditya7bgp@gmail.com
author: Your Name
description: "Balance is at the very core of just about every activity we do, be it walking, standing, running or dancing,
yet very few of us actually work at improving it. Freefeet just helps."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/freefeet.in
